tCXX = g++
CXXFLAGS = -std=c++14 -Wall -g
EXEC = a
MAINOBJ = 1858B.cpp
OBJECTS = ${MAINOBJ}


${EXEC}: ${OBJECTS}
		${CXX} ${CXXFLAGS} -g ${OBJECTS} -o ${EXEC}

.PHONY: clean

clean:
		rm ${OBJECTS} ${EXEC} 